/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intefaz;


import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import javax.swing.*;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;




/**
 *
 * @author adcd_
 */
public class CargaDeArchivo extends javax.swing.JFrame {

    /**
     * Creates new form CargaDeArchivo
     */
    public CargaDeArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCargarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Cargue un archivo JSON");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        botonCargarArchivo.setText("Cargar Archivo");
        botonCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona un archivo JSON");

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();

            try (FileReader reader = new FileReader(archivoSeleccionado)) {
                Gson gson = new Gson();
                JsonObject metroDeCaracas = gson.fromJson(reader, JsonObject.class);

                System.out.println("Archivo JSON cargado exitosamente.");

                // Verificar si contiene el sistema "Metro de Caracas"
                if (metroDeCaracas.has("Metro de Caracas")) {
                    JsonElement lineasElement = metroDeCaracas.get("Metro de Caracas");

                    if (lineasElement != null && lineasElement.isJsonArray()) {
                        System.out.println("El sistema de metro es un arreglo. Procesando cada elemento...");

                        for (JsonElement lineaElement : lineasElement.getAsJsonArray()) {
                            if (lineaElement.isJsonObject()) {
                                JsonObject lineasObject = lineaElement.getAsJsonObject();

                                for (String nombreLinea : lineasObject.keySet()) {
                                    System.out.println("Línea: " + nombreLinea);
                                    JsonElement estacionesElement = lineasObject.get(nombreLinea);

                                    // Verificar si las estaciones están en formato de objeto o de array
                                    if (estacionesElement != null && estacionesElement.isJsonObject()) {
                                        JsonObject estacionesObject = estacionesElement.getAsJsonObject();
                                        String estacionAnterior = "N/A";
                                        boolean primeraEstacion = true;

                                        for (String estacionNombre : estacionesObject.keySet()) {
                                            System.out.println("Procesando estación: " + estacionNombre);
                                            JsonElement estacionData = estacionesObject.get(estacionNombre);

                                            if (estacionData != null && estacionData.isJsonObject()) {
                                                JsonObject estacionConectada = estacionData.getAsJsonObject();
                                                for (String conexionNombre : estacionConectada.keySet()) {
                                                    String conexionLinea = estacionConectada.get(conexionNombre).getAsString();
                                                    System.out.println("Estación conexión: " + conexionNombre + " (conexión: " + conexionLinea + ")");
                                                }
                                            } else if (estacionData != null && estacionData.isJsonPrimitive()) {
                                                // Estación regular
                                                if (!primeraEstacion) {
                                                    System.out.println("Estación regular: " + estacionNombre + " - Anterior: " + estacionAnterior);
                                                }
                                                estacionAnterior = estacionNombre;
                                                primeraEstacion = false;
                                            }
                                        }
                                    } else if (estacionesElement != null && estacionesElement.isJsonArray()) {
                                        System.out.println("Estaciones de la línea en formato de array.");
                                        for (JsonElement estacionElement : estacionesElement.getAsJsonArray()) {
                                            if (estacionElement.isJsonPrimitive()) {
                                                System.out.println("Estación: " + estacionElement.getAsString());
                                            } else if (estacionElement.isJsonObject()) {
                                                // Tratamiento especial para estaciones en formato de objeto
                                                JsonObject estacionObj = estacionElement.getAsJsonObject();
                                                for (String estacionNombre : estacionObj.keySet()) {
                                                    System.out.println("Estación: " + estacionNombre);
                                                }
                                            }
                                        }
                                    } else {
                                        System.out.println("Formato inesperado para las estaciones de la línea " + nombreLinea);
                                    }
                                }
                            }
                        }
                    } else {
                        System.out.println("El formato de 'Metro de Caracas' no es compatible o está vacío.");
                    }
                } else {
                    System.out.println("'Metro de Caracas' no encontrado en el JSON.");
                }

            } catch (IOException e) {
                System.out.println("Error leyendo el archivo");
                e.printStackTrace();
            } catch (Exception e) {
                System.out.println("Error procesando el archivo");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_botonCargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaDeArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaDeArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaDeArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaDeArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaDeArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
