/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intefaz;
import edd.*;
/**
 *
 * @author guante
 */
public class CoberturaSucursal extends javax.swing.JFrame {
    static Grafo test;
    /**
     * Creates new form CoberturaSucursal
     */
    public CoberturaSucursal(Grafo g) {
        this.test = g;
        initComponents();
        this.setVisible(true);
        String[] estaciones = this.test.verSucursales();
        this.comboBoxSucursal.removeAllItems();
        for (int i = 0; i < estaciones.length; i++) {
            if(estaciones[i]!= null){
                this.comboBoxSucursal.addItem(estaciones[i]);}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCoberturaSucursal = new javax.swing.JButton();
        comboBoxSucursal = new javax.swing.JComboBox<>();
        botonRevisarCobertura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSucursal = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCoberturaSucursal.setText("VER COBERTURA SUCURSAL");
        botonCoberturaSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCoberturaSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(botonCoberturaSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        comboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        botonRevisarCobertura.setText("REVISAR COBERTURA SUCURSAL");
        botonRevisarCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevisarCoberturaActionPerformed(evt);
            }
        });
        jPanel1.add(botonRevisarCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("COBRETURA DE SUCURSAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        textAreaSucursal.setColumns(20);
        textAreaSucursal.setRows(5);
        jScrollPane1.setViewportView(textAreaSucursal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 450, 320));

        back.setText("ATRAS");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Menu v = new Menu (test);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void botonCoberturaSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCoberturaSucursalActionPerformed
        this.textAreaSucursal.setText(this.test.profundidad(this.comboBoxSucursal.getSelectedItem().toString()));
    }//GEN-LAST:event_botonCoberturaSucursalActionPerformed

    private void botonRevisarCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevisarCoberturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRevisarCoberturaActionPerformed

    private void comboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoberturaSucursal(test).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton botonCoberturaSucursal;
    private javax.swing.JButton botonRevisarCobertura;
    private javax.swing.JComboBox<String> comboBoxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaSucursal;
    // End of variables declaration//GEN-END:variables
}
