/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intefaz;

import edd.*;

/**
 *
 * @author guante
 */
public class ColocarSucursal extends javax.swing.JFrame {

    static Grafo test;

    /**
     * Creates new form ColocarSucursal
     */
    public ColocarSucursal(Grafo g) {
        this.test = g;
        initComponents();
        this.setVisible(true);
        String[] estaciones = this.test.arregloPosition();
        this.selectorEstaciones.removeAllItems();
        for (int i = 0; i < estaciones.length; i++) {
            this.selectorEstaciones.addItem(estaciones[i]);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSucursales = new javax.swing.JButton();
        selectorEstaciones = new javax.swing.JComboBox<>();
        bacl = new javax.swing.JButton();
        botonSucursales1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("COLOCAR SUCURSAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        botonSucursales.setText("COLOCAR SUCURSAL SELECIONADA");
        botonSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSucursalesActionPerformed(evt);
            }
        });
        jPanel1.add(botonSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 30));

        selectorEstaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectorEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorEstacionesActionPerformed(evt);
            }
        });
        jPanel1.add(selectorEstaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, -1));

        bacl.setText("ATRAS");
        bacl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baclActionPerformed(evt);
            }
        });
        jPanel1.add(bacl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        botonSucursales1.setText("QUITAR SUCURSAL SELECIONADA");
        botonSucursales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSucursales1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSucursales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSucursalesActionPerformed
        this.test.searchGraf(this.selectorEstaciones.getSelectedItem().toString()).setSucursal(true);
    }//GEN-LAST:event_botonSucursalesActionPerformed

    private void baclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baclActionPerformed
        Menu v = new Menu(test);
        this.dispose();
    }//GEN-LAST:event_baclActionPerformed

    private void selectorEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorEstacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorEstacionesActionPerformed

    private void botonSucursales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSucursales1ActionPerformed
        // TODO add your handling code here:
        this.test.searchGraf(this.selectorEstaciones.getSelectedItem().toString()).setSucursal(false);

    }//GEN-LAST:event_botonSucursales1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColocarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColocarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColocarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColocarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColocarSucursal(test).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bacl;
    private javax.swing.JButton botonSucursales;
    private javax.swing.JButton botonSucursales1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectorEstaciones;
    // End of variables declaration//GEN-END:variables
}
